variables:
  CI_IMAGE_TAG: '-cuda'

stages:
  - test
  - postprocess

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/common.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/test_v0.7.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/test_v1.0.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/test_dev.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/postprocess_coverage.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/postprocess_documentation.yml'

test:dev:
  allow_failure: true
